const ELO_DEFAULT = 65;
const ELO_SIZE_ADVANTAGE_PER_PLAYER = 20;
const ELO_K_FACTOR = 1;
const WIN_PROB_SIZE_MULTIPLIER_BASE = 1.2;
const ELO_BETA_FACTOR = 0.5;
const ELO_SCALE = 30;
const MATCH_COUNT_FACTOR = 12;

module.exports = {
  ELO_DEFAULT,
  ELO_SIZE_ADVANTAGE_PER_PLAYER,
  ELO_K_FACTOR,
  WIN_PROB_SIZE_MULTIPLIER_BASE,
  ELO_BETA_FACTOR,
  ELO_SCALE,
  MATCH_COUNT_FACTOR,
};