const ELO_DEFAULT = 500;
const ELO_SIZE_ADVANTAGE_PER_PLAYER = 250;
const ELO_K_FACTOR = 4;
const WIN_PROB_SIZE_MULTIPLIER_BASE = 1.2;
const ELO_DIVISOR = 400;

module.exports = {
  ELO_DEFAULT,
  ELO_SIZE_ADVANTAGE_PER_PLAYER,
  ELO_K_FACTOR,
  WIN_PROB_SIZE_MULTIPLIER_BASE,
  ELO_DIVISOR,
};